services:
  - mongodb

language: node_js
node_js:
  - "0.12"

before_install: npm install -g grunt-cli

install:
 - npm install

# .travis.yml
before_script:
  - sleep 15

branches:
  only:
    - master
    - develop

